### ISSUE TITLE
turtle.craft()

### ISSUE THREAD

**Issue by kizeren** [Inksaver/Minecraft-Toolkit#1]
As of 1.21.1 turtle.craft() doesn't not show up as a useable function.

Found on tk.lua line 9450 I believe it was.

**Comment by Inksaver** [comment]
The toolkit version here is dated 20230927.1400 as I usually put updated versions on Pastebin where they can be directly downloaded from within ccTweaked. I will update all the files here later today but it is currently working with cc-tweaked-1.21.1-forge-1.113.1.jar and neoforge.
The current version is 20241111.1400 but is being updated frequently. The best source is https://pastebin.com/8qbeZevX which loads them automatically and has a list of all pastebin urls starting on line 249
tk.lua turtle.craft() is currently on line 9704 and 10929
clsTurtle.lua turtle.craft() is currently on line 897, 906, 920 and 1034

**Comment by kizeren** [comment]
I finally got it on the right version but still the same error.  I am guessing something is missing from the fabric install.

cc-tweaked-1.21.1-fabric-1.113.1.jar
fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar

After doing some testing.  It would appear I missed something.  After crafting a mining turtle.  You have to put the turtle back in your craft window and add a crafting table to it.  Can't insert into the slot or it doesn't register as a crafting turtle and thus can't use turtle.craft().


![Screenshot_2024-11-14_09-07-24](https://github.com/user-attachments/assets/4b059cce-2062-46ee-99a2-e4c1fdd2ef24)
![Screenshot_2024-11-14_09-12-08](https://github.com/user-attachments/assets/1cac244d-d4b1-42c9-a044-911146498889)

**Comment by Inksaver** [comment]
I suspect this is a bug in the fabric version of ccTweaked, and worth reporting it on their github.
As a workaround, are you able to place the crafting table in slot 1 and from the lua interpreter use turtle.equipRight() followed by adding a log, then turtle.craft()?
If that works, I could add a workaround.

**Comment by kizeren** [comment]
Ok.  Yes using ```turtle.equipLeft()``` worked.

**Comment by Inksaver** [comment]
I added the line T:setEquipment() as line 15867 (see screenshot)
When you start tk it unloads all equipment and replaces it. Could you check if that works?
![CCTweaked bug fix](https://github.com/user-attachments/assets/66de013a-2fa1-4f32-933e-973e0c87a203)

**Comment by kizeren** [comment]
It seems to have fixed it.  Let me use it for rest of the week and I'll report back.

**Comment by kizeren** [comment]
Okay after a bit of testing and breaking.  This seems to have fixed the issue.  Thanks!
